### PR TITLE
Protractor fix SpecReporter is not a constructor

### PR DESCRIPTION
**Pull request by Urbiwanus**
Fixed 
SpecReporter is not a constructor issue

### CODE REVIEW

**Comment by lathonez** [comment]
Can you give some information on what the issue you're solving here actually is please?

Protractor.conf comes from ng-cli upstream, so I'd need to understand why we need this change but they don't.  

Thanks

**Comment by Urbiwanus** [comment]
I tried your code and i always got following error 

`11:05:20] E/launcher - Error: TypeError: SpecReporter is not a constructor
    at onPrepare (/Users/kaiseran/projects/mysearchapp/protractor.conf.js:32:34)
    at q_1.Promise (/Users/kaiseran/projects/mysearchapp/node_modules/protractor/lib/util.ts:47:39)
    at Function.promise (/Users/kaiseran/projects/mysearchapp/node_modules/q/q.js:682:9)
    at Object.runFilenameOrFn_ (/Users/kaiseran/projects/mysearchapp/node_modules/protractor/lib/util.ts:38:10)
    at plugins_.onPrepare.then (/Users/kaiseran/projects/mysearchapp/node_modules/protractor/lib/runner.ts:85:21)
    at _fulfilled (/Users/kaiseran/projects/mysearchapp/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/kaiseran/projects/mysearchapp/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/kaiseran/projects/mysearchapp/node_modules/q/q.js:796:13)
    at /Users/kaiseran/projects/mysearchapp/node_modules/q/q.js:556:49
    at runSingle (/Users/kaiseran/projects/mysearchapp/node_modules/q/q.js:137:13)
[11:05:20] E/launcher - Process exited with error code 100

The change it protractor.conf.js fixed the problem

Best regards`

**Comment by lathonez** [comment]
Probably an issue with versioning.

Compare your package.json with ours.

Iirc someone has reported this issue before, try searching for it under
issues.

**Comment by lathonez** [comment]
If the issue persists please raise an issue so we can address it correctly. If a code change is needed an upstream PR to ng-cli will be required.

**Pull request closed without merging**
