### PR TITLE
Minor & patch version bump

### PR DESCRIPTION
**Pull request by pvdyck**
I don't know if you follow some guidelines regarding latest versions, but this pass all tests.

### CODE REVIEW

**Comment by lathonez** [comment]
I upgrade deps whenever I take a new ionic version. Happy enough to take them now.

What's the change to `gulpfile.ts` about? "Needed" doesn't tell me very much :)

**Comment by pvdyck** [comment]
well ... the change is needed and I don't remember why actually ;-)
don't apply it then you'll have the error (I think you can't pass the promise just like that)
give it a try !

**Comment by lathonez** [comment]
Works fine here. If you're talking about `npm run karma`.

**Comment by pvdyck** [comment]
Indeed, I had an error with npm run karma ...  maybe it disappeared by upgrading the packages ;-)

**Comment by lathonez** [comment]
Nope, I've not done anything with your PR (or updated any packages) and it
works fine for me.

Can you remove the superfluous change and I'll merge.

On 8 Sep 2016 10:55, "pvdyck" <notifications@github.com> wrote:

>

> Indeed, I had an error with npm run karma ... maybe it disappeared by
upgrading the packages ;-)
>
> —
> You are receiving this because you commented.
>
> Reply to this email directly, view it on GitHub
<https://github.com/lathonez/clicker/pull/143#issuecomment-245463948>, or
mute the thread

**Comment by lathonez** [comment]
Or is it updating the packages that makes this change necessary?

**Comment by lathonez** [comment]
After testing before and after the package upgrade, could find no reason for the "needed" change you made. So removed it in the merge.

**Comment by pvdyck** [comment]
Good news that the change isn't needed anymore... I will rebase then.

**Pull request merged**
