### PR TITLE
clean up

### PR DESCRIPTION
**Pull request by hfwittmann**
remove unneccesary import

### CODE REVIEW

**Comment by hfwittmann** [comment]
I am not sure what's gone wrong. I only tried to delete one line in storage.spec.ts, namely

 import { StorageMock }    from './mocks';

Locally all the tests run fine. Should I try again?

**Comment by lathonez** [comment]
Appveyor failed to load the webdriver, despite it being in the post install npm steps _and_ being called explicitly before the tests run.

No idea why. Am rebuilding now (just to see what happens).

Will merge this regardless shortly. Thanks for the contribution

**Comment by lathonez** [comment]
.. just rebuilding sorted it 👏 appveyor.

**Comment by hfwittmann** [comment]
Excellent

**Pull request merged**
