### PR TITLE
Circle CI Configuration

### PR DESCRIPTION
**Pull request by stonelasley**
This should be a good start to building on CircleCi. I left off the deployment step because it would be a shot in the dark. 

A couple notes:

1. ionic state clear seems to have been removed? 
2. I am running install ionic@latest which I dislike, however, there is [no way to squelch the CLI update prompt](https://github.com/ionic-team/ionic-cli/issues/2517) which has been breaking my builds. I'm a not super enthusiastic about this. Has anyone come up with a better approach?
3. Timezone probably needs to be updated or removed all-together.

### CODE REVIEW

**Comment by stonelasley** [comment]
link to my last build https://circleci.com/gh/stonelasley/clicker/15

**Comment by lathonez** [comment]
Hey,

This is excellent - thanks a lot.

Odd - we're using circle for another Ionic based project using ionic@someversion and it's not been a problem.

Will investigate why, merge your config with ours (your Chrome set up is a lot better than mine) and get this up on Circle.

Stephen

**Comment by lathonez** [comment]
Everything is up and running on circle 2.0. Thanks again for this.

**Comment by stonelasley** [comment]
@lathonez, for as much as I've referenced this project it's the least I can do. Thanks!

**Pull request merged**
